/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author spsither
 */
public class Home extends javax.swing.JFrame {
    private JFileChooser fc;
    private Admin admin;
    
    /**
     * Creates new form Home
     * @param admin
     */
    public Home(Admin admin) {
        initComponents();
        invalidMessage.put(0, "Enter name");
        invalidMessage.put(1, "Enter address line 1");    
        invalidMessage.put(2, "Enter City");
        invalidMessage.put(3, "Enter State");
        invalidMessage.put(4, "Enter valid pin, pin value must be numaric");
        invalidMessage.put(5, "Select a Country");
        invalidMessage.put(6, "Enter a Expiry Date");
        invalidMessage.put(7, "Enter valid number of copy");
        
        this.admin = admin;
        
       
        loadBT.doClick();
        generateSummary();
       
    }

    HashMap invalidMessage = new HashMap();
     
    //String file = "/User/spsither/Desktop/out.txt";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerTB = new javax.swing.JTable();
        loadBT = new javax.swing.JButton();
        orderCB = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        saveBT = new javax.swing.JButton();
        printBT = new javax.swing.JButton();
        expCB = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        countriesCB = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        noOfCopyTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        expDateDC = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        insertBT = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        pinTF = new javax.swing.JTextField();
        address1TF = new javax.swing.JTextField();
        address2TF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        address3TF = new javax.swing.JTextField();
        address4TF = new javax.swing.JTextField();
        cityTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stateTF = new javax.swing.JTextField();
        billRB = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        errorLB = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        summaryTA = new javax.swing.JTextArea();
        newPwd = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab.setToolTipText("");

        customerTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Country", "ExpDate", "NoOfCopy", "BillOrComp", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerTB);

        loadBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/load24.png"))); // NOI18N
        loadBT.setText("load");
        loadBT.setToolTipText("load records in table");
        loadBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTActionPerformed(evt);
            }
        });

        orderCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Country", "NoOfCopy", "ExpDate" }));
        orderCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCBActionPerformed(evt);
            }
        });

        jLabel12.setText("Order by");

        jToolBar1.setRollover(true);

        saveBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/save24.png"))); // NOI18N
        saveBT.setToolTipText("Save all records as text");
        saveBT.setFocusable(false);
        saveBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTActionPerformed(evt);
            }
        });
        jToolBar1.add(saveBT);

        printBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/print24.png"))); // NOI18N
        printBT.setToolTipText("Print all the records");
        printBT.setFocusable(false);
        printBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        printBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        printBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBTActionPerformed(evt);
            }
        });
        jToolBar1.add(printBT);

        expCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Not Expired", "Expired" }));
        expCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expCBActionPerformed(evt);
            }
        });

        jLabel13.setText("Select by");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loadBT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadBT)
                    .addComponent(orderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(expCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab.addTab("view", jPanel1);

        countriesCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-select-", "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Republic of the", "Congo, Democratic Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "St. Kitts and Nevis", "St. Lucia", "St. Vincent and The Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Tibet", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom (UK)", "United States of America (USA)", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City (Holy See)", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe" }));
        countriesCB.setNextFocusableComponent(billRB);
        countriesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countriesCBActionPerformed(evt);
            }
        });

        jLabel9.setText("number of copy");

        noOfCopyTF.setText("1");
        noOfCopyTF.setNextFocusableComponent(expDateDC);

        jLabel1.setText("name");

        jLabel10.setText("expiry date");

        jLabel2.setText("address line 1");

        jLabel3.setText("address line 2");

        jLabel4.setText("address line 3");

        jLabel5.setText("address line 4");

        expDateDC.setNextFocusableComponent(insertBT);

        jLabel6.setText("city");

        insertBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/new24.png"))); // NOI18N
        insertBT.setText("insert");
        insertBT.setNextFocusableComponent(nameTF);
        insertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBTActionPerformed(evt);
            }
        });

        nameTF.setNextFocusableComponent(address1TF);

        pinTF.setNextFocusableComponent(countriesCB);

        address1TF.setNextFocusableComponent(address2TF);

        address2TF.setNextFocusableComponent(address3TF);

        jLabel11.setText("pin");

        address3TF.setNextFocusableComponent(address4TF);

        address4TF.setNextFocusableComponent(cityTF);

        cityTF.setNextFocusableComponent(stateTF);

        jLabel7.setText("state");

        stateTF.setNextFocusableComponent(pinTF);

        buttonGroup1.add(billRB);
        billRB.setSelected(true);
        billRB.setText("BILL");
        billRB.setNextFocusableComponent(noOfCopyTF);
        billRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("COMP");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("country");

        errorLB.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        errorLB.setForeground(new java.awt.Color(255, 51, 51));

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");

        jLabel17.setForeground(new java.awt.Color(255, 51, 0));
        jLabel17.setText("*");

        jLabel18.setForeground(new java.awt.Color(255, 51, 0));
        jLabel18.setText("*");

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("* Required fields");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(address2TF)
                                            .addComponent(address1TF)
                                            .addComponent(address3TF)
                                            .addComponent(address4TF)
                                            .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(stateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(billRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(42, 42, 42)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(noOfCopyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(expDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21))))
                                    .addComponent(insertBT)
                                    .addComponent(errorLB, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(countriesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pinTF, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)))))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(address1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(address2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(noOfCopyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(address3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(address4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel10))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(billRB)
                                    .addComponent(jRadioButton2))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(expDateDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))
                                .addGap(33, 33, 33)
                                .addComponent(insertBT)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(stateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(errorLB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countriesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel19))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        tab.addTab("insert", jPanel2);

        jButton1.setText("Change your Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Send a Bug Report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        summaryTA.setEditable(false);
        summaryTA.setColumns(20);
        summaryTA.setRows(5);
        jScrollPane2.setViewportView(summaryTA);

        jButton3.setText("reload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(18, 18, 18)
                                    .addComponent(newPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButton2)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(newPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(16, 16, 16))
        );

        tab.addTab("others", jPanel3);

        jMenu1.setText("Options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/new24.png"))); // NOI18N
        jMenuItem1.setText("insert");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tr/load24.png"))); // NOI18N
        jMenuItem2.setText("load");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customerTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTBMouseClicked
    int row = customerTB.getSelectedRow();
    long id = (long) customerTB.getModel().getValueAt(row, 6);
    String name = (String) customerTB.getModel().getValueAt(row, 0);
    Object[] options = {"Edit",
                    "Delete",
                    "Cancel"};
int n = JOptionPane.showOptionDialog(this,
    "What youd you like to do with "+name+"'s record?",
    "Message",
    JOptionPane.YES_NO_CANCEL_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    options,
    options[2]);
    //System.out.println(""+n);

    switch(n){
        case 0:
            new Edit(id,this).setVisible(true);
            break;
        case 1:
            delete(id,name);
            load();
            break;
        
            
    }

    }//GEN-LAST:event_customerTBMouseClicked

    private void loadBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTActionPerformed
        showAll();
    }//GEN-LAST:event_loadBTActionPerformed

    private void insertBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBTActionPerformed
        
    Customer cus = new Customer();
    Boolean [] valid;
        valid = new Boolean[8];
    valid[0] = cus.setName(nameTF.getText().trim());
    valid[1] = cus.setAddressLine1(address1TF.getText().trim());
    cus.setAddressLine2(address2TF.getText().trim());
    cus.setAddressLine3(address3TF.getText().trim());
    cus.setAddressLine4(address4TF.getText().trim());
    valid[2] = cus.setCity(cityTF.getText().trim());
    valid[3] = cus.setState(stateTF.getText().trim());
    valid[4] = cus.setPin(pinTF.getText().trim());
    valid[5] = cus.setCountry((String)countriesCB.getSelectedItem());
    if(billRB.isSelected()){
        cus.setBillOrComp("BILL");
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        if(expDateDC.getDate() != null){
            String dt = sdf.format(expDateDC.getDate());
            valid[6] =  cus.setExpDate(dt);
         
        }
        else{
            valid[6] = false;
        }
    }
    else{
        cus.setBillOrComp("COMP");
        
        valid[6] = true;
    }
    
    valid[7] = cus.setNoOfCopy(noOfCopyTF.getText().trim());
        
       
       if(validate(valid)){
            DBConnector con = new DBConnector();
            if(con.insert(cus)){
                JOptionPane.showMessageDialog(rootPane, "INSERTED\n"+cus);
                loadBT.doClick();
                clear();
            }
            con.close();
       }
       
       

    }//GEN-LAST:event_insertBTActionPerformed

    void clear(){
        nameTF.setText("");
        address1TF.setText("");
        address2TF.setText("");
        address3TF.setText("");
        address4TF.setText("");
        cityTF.setText("");
        stateTF.setText("");
        pinTF.setText("");
        countriesCB.setSelectedIndex(0);
        billRB.setSelected(true);
        noOfCopyTF.setText("1");
        expDateDC.setEnabled(true);
        expDateDC.setCalendar(null);
        
                
    }
    Boolean validate(Boolean [] val){
        
        for(int i = 0 ; i < val.length; i++){
            if(!val[i]){
                errorLB.setText((String) invalidMessage.get(i));
                return false;
            }
        }
        
        errorLB.setText("");
        return true;
    }
    
    private void countriesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countriesCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countriesCBActionPerformed

    private void billRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billRBActionPerformed
    expDateDC.setEnabled(true);        // TODO add your handling code here:
    jLabel21.setVisible(true);
    }//GEN-LAST:event_billRBActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
    expDateDC.setEnabled(false);
    jLabel21.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void saveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTActionPerformed
        fc = new JFileChooser();
        DBConnector con = new DBConnector();
         String query = "";
        switch(expCB.getSelectedIndex()){
            case 0:
                query = "select * "+
                "from customer order by "+orderCB.getSelectedItem()+";";
                break;
            case 1:
                query = "select * "+
                "from customer where ExpDate >= now() or ExpDate is null order by "+orderCB.getSelectedItem()+";";
                break;
            case 2:
                query = " select * "+
                "from customer where ExpDate < now() order by "+orderCB.getSelectedItem()+";";
                break;    
            
        }
        con.executeQuery(query);
        
        //con.executeQuery("select * from customer order by "+orderCB.getSelectedItem()+";");
        Customer cus = new Customer();
        try {
            //
            fc.setSelectedFile(new File("Records.txt"));
            int returnVal = fc.showSaveDialog(rootPane);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
                //
                try ( //This is where a real application would open the file.
                        PrintWriter outStream = new PrintWriter(file)) {
                    //
                    while(con.rs.next()){
                        cus.load(con.rs);
                        outStream.print(cus);
                        cus.clear();
                    }
                    //
                }
            JOptionPane.showMessageDialog(rootPane, "Records saved to "+file);
            
        } 
            
        } catch (FileNotFoundException | SQLException ex){
            
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_saveBTActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        tab.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        tab.setSelectedIndex(0);
        orderCB.setSelectedIndex(0);
        loadBT.doClick();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void printBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBTActionPerformed
        
        Print print = new Print(orderCB.getSelectedItem(),expCB.getSelectedIndex());
        print.setVisible(true);
        
        
    }//GEN-LAST:event_printBTActionPerformed

    private void orderCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCBActionPerformed
showAll();
// TODO add your handling code here:
    }//GEN-LAST:event_orderCBActionPerformed

    private void expCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expCBActionPerformed
showAll();
// TODO add your handling code here:
    }//GEN-LAST:event_expCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int reply = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to change your password?");
       if (reply == JOptionPane.YES_OPTION){
           if(newPwd.getText().length() < 5){
               JOptionPane.showMessageDialog(rootPane, "Password should be of length greater than four", "Error", JOptionPane.ERROR_MESSAGE);
               newPwd.setText("");
               return;
           }
           admin.setPassword(newPwd.getText());
           DBConnector connector = new DBConnector();
           
           if(!connector.changePwd(admin)){
               JOptionPane.showMessageDialog(rootPane, "Sorry, cound not change password. Try Later.", "Error", JOptionPane.ERROR_MESSAGE);
           }else{
               JOptionPane.showMessageDialog(rootPane, "Password Successfully changed.");
           }
           newPwd.setText("");
           connector.close();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Please mail your troubles to spsither@gmail.com");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    generateSummary();
    }//GEN-LAST:event_jButton3ActionPerformed

   private void delete(long id,String name){
        Object[] options = {"Yes",
                    "No"};
int n = JOptionPane.showOptionDialog(this,
    "Are you sure you want to delete "+name+" ("+id+")?",
    "Conferm",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,
    options,
    options[1]);
    System.out.println("Delete:"+n);

    if(n == 0){
        DBConnector con = new DBConnector();
        con.deleteRecord(id);
        con.close();
        loadBT.doClick();
    }
        
        
    }
   
    private void showAll(){
        DBConnector connection = new DBConnector();
        String query = "";
        switch(expCB.getSelectedIndex()){
            case 0:
                query = "select Name, Concat(coalesce(AddressLine1,''),',',coalesce(AddressLine2,''),"+
                "',', coalesce(AddressLine3,''),',', coalesce(AddressLine4,''),',', coalesce(City,''),',', "+
                "coalesce(State,''),',', coalesce(Pin,'')) as Address, Country, ExpDate, NoOfCopy, BillOrComp ,id "+
                "from customer order by "+orderCB.getSelectedItem()+";";
                break;
            case 1:
                query = "select Name, Concat(coalesce(AddressLine1,''),',',coalesce(AddressLine2,''),"+
                "',', coalesce(AddressLine3,''),',', coalesce(AddressLine4,''),',', coalesce(City,''),',', "+
                "coalesce(State,''),',', coalesce(Pin,'')) as Address, Country, ExpDate, NoOfCopy, BillOrComp ,id "+
                "from customer where ExpDate >= now() or ExpDate is null order by "+orderCB.getSelectedItem()+";";
                break;
            case 2:
                query = "select Name, Concat(coalesce(AddressLine1,''),',',coalesce(AddressLine2,''),"+
                "',', coalesce(AddressLine3,''),',', coalesce(AddressLine4,''),',', coalesce(City,''),',', "+
                "coalesce(State,''),',', coalesce(Pin,'')) as Address, Country, ExpDate, NoOfCopy, BillOrComp ,id "+
                "from customer where ExpDate < now() order by "+orderCB.getSelectedItem()+";";
                break;    
            
        }
        connection.executeQuery(query);
        customerTB.setModel(DbUtils.resultSetToTableModel(connection.rs));
        customerTB.getColumnModel().getColumn(0).setPreferredWidth(20);
        customerTB.getColumnModel().getColumn(4).setPreferredWidth(3);
        customerTB.getColumnModel().getColumn(6).setPreferredWidth(3);
        connection.close();
    }
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1TF;
    private javax.swing.JTextField address2TF;
    private javax.swing.JTextField address3TF;
    private javax.swing.JTextField address4TF;
    private javax.swing.JRadioButton billRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityTF;
    private javax.swing.JComboBox countriesCB;
    private javax.swing.JTable customerTB;
    private javax.swing.JLabel errorLB;
    private javax.swing.JComboBox expCB;
    private com.toedter.calendar.JDateChooser expDateDC;
    private javax.swing.JButton insertBT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton loadBT;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField newPwd;
    private javax.swing.JTextField noOfCopyTF;
    private javax.swing.JComboBox orderCB;
    private javax.swing.JTextField pinTF;
    private javax.swing.JButton printBT;
    private javax.swing.JButton saveBT;
    private javax.swing.JTextField stateTF;
    private javax.swing.JTextArea summaryTA;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
    void load(){
        loadBT.doClick();
    }

    private void generateSummary() {
                                
        DBConnector connection = new DBConnector();
        long strength = connection.getStrength();
        long expiredStrength = connection.getExpStrength();
        StringBuffer countryWiseStrength = connection.getCountryWiseStrength();
        
        summaryTA.setText("Total number of subscribers:   " + strength + "\n" +
                          "Number of Expired subscribers: " + expiredStrength + "\n\n" +
                          "\tNumber of Subscriber in each Country\n"+ countryWiseStrength );
        
        
        connection.close();
    }
    
   
    
}
 

